### ISSUE TITLE
Use map to navigate to a certain panorama/point

### ISSUE THREAD

**Issue by arash-arbaya** [amosproj/amos-ss2021-3d-viewer#13]
## User story
1. As a user
2. I want to click on a point in the map
3. So that the currently displayed panorama is changed to the one, which is closest to the clicked position.

## Acceptance criteria
* after a click on the map, the panorama, which is closest to the clicked location is displayed
* this moving works in both states: when the map is small and when the map is in 'fullscreen' mode.
* its okay if the map is always centered on the currently displayed panorama
* double clicking is required to move the position/to change the panorama.

## Definition of done
* Code has been peer reviewed
* Documentation has been updated
* Code has been included into the release (candidate)
* No syntax / runtime errors
* Code is well structured and formatted

**Comment by Mm24** [comment]
The user story is completed by @clairebb1005 and peer reviewd by @Mm24

**Comment by Mm24** [comment]
It is ready to move to awaiting review :-)
