### ISSUE TITLE
Refactor Viewer to fit API Architecture

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#19]
## User story
1. As a product owner
2. I want to have the basic viewer structure
3. So that it matches the API documentation

## Acceptance criteria
* ViewerPanoAPI implements the view method and the scene property
* ViewerViewState is implemented as described in the docu

## Definition of done
* Added only after week 5
* The same for all features

**Comment by leonopulos** [comment]
As part of last weeks sprint, I had already created the ViewerViewState file in the correct location, and added the class with it's 3 variables. The class is also already imported in the main.js file. You can find the commit [here](https://github.com/amosproj/amos-ss2021-3d-viewer/pull/22/commits/525ec583dbbdf20045b92d2f8ee554ae6f29db4d).

However what still needs to be done, is ViewerViewState objects need to actually be used.
So certain parts of the implementation in the main.js need to be refactored. 

For example the ´longitude´ and ´latitude´ variables should be gone, in exchange for a ViewerViewState object. 
The same can be done with ´onPointerDownLon´ and -Lat.
Of course this means changing the code in other spots too, wherever the variables are used right now, it needs to be replaced with the correct use of a ViewerViewSate Object.
