### ISSUE TITLE
Display current position and viewing direction

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#37]
## User story
1. As a user
2. I want to see in which direction I am currently looking
3. So that I have a feeling of orientation in the room

## Acceptance criteria
* The viewing direction is displayed
* the current position is displayed

## Definition of done
* Code has been peer reviewed
* Documentation has been updated
* Code has been included into the release (candidate)
* No syntax / runtime errors
* Code is well structured and formatted

**Comment by Mm24** [comment]
The appoach taken dioes not correlate or was similar to the one shown in the demo. 
I would change completely the approach as taken with Stefan. 
Reaminig task:

- Create a triangular sprite according to the quartenion on the data.json
- Overlay and update that dirtection in every rotation Displacement
- Imnporve the visualization ocverlay

**Comment by Mm24** [comment]
The user story should be complete and ready to release: 

- Set the viewing direction to scale with Zoom (FOV) 
- The viewing direction updates qith Zooming pf Panorama
- The full positions on the floor are displayed as black points
- The current position and the viewing direction vertex are displayed in red

Nevertheless, when changing dataset the first lonov should be used update.

**Comment by Mm24** [comment]
THe code is fully refactor and peer reviewed
