### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#43]
## User story
1. As a customer
2. I need an instructive documentation
3. So that users know, how to install and use the 3D viewer for their purposes

## Acceptance criteria. 
* the documentation is provided in the wiki as well as in the README.md file in the root directory of the github repo.
Following questions should be answered:
* what needs to be done, to get the 3D viewer working 
* in which format do the pictures need to be? 
* which naming of the files is required? which folder structure?
* How does the user interact with the viewer? List all possible operations

## Definition of done
* Code has been peer reviewed
* Documentation has been updated
* Code has been included into the release (candidate)
* No syntax / runtime errors
* Code is well structured and formatted

**Comment by Nes55** [comment]
Software Runtime component 

![Untitled Diagram](https://user-images.githubusercontent.com/73950780/119265928-f7417100-bbe8-11eb-991a-5ccbbbc2ea01.png)

**Comment by Nes55** [comment]
![Capture](https://user-images.githubusercontent.com/73950780/119566353-56e77a00-bdab-11eb-9c39-d771e44b59c1.JPG)


![Capture2](https://user-images.githubusercontent.com/73950780/119566656-acbc2200-bdab-11eb-9e7c-7ddbe82d9e73.JPG)

![Capture3](https://user-images.githubusercontent.com/73950780/119566690-b5acf380-bdab-11eb-8fc9-5aa39b30bc37.JPG)

**Comment by Nes55** [comment]
![n](https://user-images.githubusercontent.com/73950780/119571362-8d27f800-bdb1-11eb-9c91-eb18b63ada41.jpg)

![Capture4](https://user-images.githubusercontent.com/73950780/119571712-fc055100-bdb1-11eb-98dc-bcafb0696dd1.JPG)

**Comment by Nes55** [comment]
![Capture5](https://user-images.githubusercontent.com/73950780/119573179-3243d000-bdb4-11eb-9e8b-6b4d027752a6.JPG)

**Comment by Nes55** [comment]
![Picture10](https://user-images.githubusercontent.com/73950780/119861251-769bb100-bf17-11eb-806f-52d8b7d03861.png)

**Comment by Nes55** [comment]
![n](https://user-images.githubusercontent.com/73950780/119861956-41439300-bf18-11eb-9891-2ef3365abf21.jpg)

**Comment by Nes55** [comment]
![Picture1](https://user-images.githubusercontent.com/73950780/119883511-eb7ae500-bf2f-11eb-9ab1-9a8f385004b5.png)

**Comment by Nes55** [comment]
![Camera rotation](https://user-images.githubusercontent.com/73950780/120026007-c0f16080-bff1-11eb-98fa-3c93fcdf3779.JPG)
![camera view from diffe](https://user-images.githubusercontent.com/73950780/120026030-c6e74180-bff1-11eb-8141-f64ed5eda10a.JPG)
![Camera rotation](https://user-images.githubusercontent.com/73950780/120026045-ccdd2280-bff1-11eb-8b63-319e14a5b42b.JPG)
![camera view from diffe](https://user-images.githubusercontent.com/73950780/120026075-d5355d80-bff1-11eb-9903-5a2aa24b0195.JPG)

**Comment by Nes55** [comment]
![camera view from diffe](https://user-images.githubusercontent.com/73950780/120028728-5b06d800-bff5-11eb-8e33-02ce32fb7781.JPG)

**Comment by Nes55** [comment]
![Camera rotation](https://user-images.githubusercontent.com/73950780/120028813-7d98f100-bff5-11eb-9a91-50cd36e6cc35.JPG)

**Comment by Nes55** [comment]
![Capture zooming](https://user-images.githubusercontent.com/73950780/120028890-9ef9dd00-bff5-11eb-95ef-3b1ea339eb3a.JPG)
