### ISSUE TITLE
Show the position of the panorama closest to the mouse

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#63]
## User story
1. As a user
2. I want to see where it´s possible to go
3. So that I can make more precise movements.

HINT: a Nearest-Neighbor classifier might be helpful, e.g. https://github.com/mljs/knn . 

## Acceptance criteria
* locations of possible panoramas are drawn as a cross on the floor.
* only the location of the closest panorama to the mouse is displayed (the panorama, which would be selected, if the user double clicked at this mouse position)
* when the mouse is around a certain panorama, the location of this panorama is displayed on the ground the ground with a 'cross' (like in google maps)
* instead of a 'cross', it´s fine to use different shape as marker, like a red ball

## Definition of done
* Code has been peer reviewed
* Documentation has been updated
* Code has been included into the release (candidate)
* No syntax / runtime errors
* Code is well structured and formatted

**Comment by Mm24** [comment]
The current development incudes a cross in the clossest position ot the mouse before but the spehere shows 

- [ x ]  only the location of the closest panorama to the mouse is displayed (the panorama, which would be selected, if the user double clicked at this mouse position)
- [ x ]    when the mouse is around a certain panorama, the location of this panorama is displayed on the ground the ground with a 'cross' (like in google maps)
-  [  ] Not whow a cross if is there is a wall @clairebb1005 @Mm24
