### ISSUE TITLE
Make Zooming and Moving of the panorama independent from the map

### ISSUE THREAD

**Issue by Kletterer** [amosproj/amos-ss2021-3d-viewer#73]
## User story
1. As a client
2. I want to "separate" the zooming interaction of map and panorama
3. So that, when my mouse is over the map, only the map is zoomed.

## Acceptance criteria
* when the mouse is over the map, rotating the mouse wheel only leads to zooming of the map but does not affect the panorama
* if the mouse is not over the map, then rotating the mouse wheel leads to zooming of the panorama
* when the user drags on the map, then only the map should be moved. The panorama should not be affected by this.

## Definition of done
* Code has been peer reviewed
* Documentation has been updated
* Code has been included into the release (candidate)
* No syntax / runtime errors
* Code is well structured and formatted

**Comment by Mm24** [comment]
In the display current direction branch the zooming of the map with the mouse wheel is disable
